services:
  backend:
    image: wisp-backend
    ports:
      - "8081:8080"
    env_file:
      - ./software_engineering_wisp/backend/.env

  frontend:
    image: wisp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend