@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype ortho

' Camada 1: Apresentação
package "Apresentação" {
    package "controladorRecomendacao" as CR
    package "View (Interface Web)" as V
}

' Camada 3: Negócio
package "Negócio" {
    package "controladorGrafos" as CG
    package "integradorMapbox" as IM
}

' Camada 4: Persistência
package "Persistência" {
    package "repositorioAtividades" as RA
    package "repositorioUsuarios" as RU
}

' Relacionamentos sincronizados com o Diagrama de Sequência
CR ..> CG
CR ..> IM

' Negócio consultando a Persistência
CG ..> RA
CG ..> RU
@enduml