@startuml
    ' Configurações de estilo acadêmico
    skinparam style strictuml 
    skinparam sequenceMessageAlign center

    ' Ordem ajustada: Usuário na esquerda, depois interface, depois controllers
    actor "Usuário Comum" as User
    boundary "View" as View
    control "Controller de Recomendação" as API
    control "Controller Grafos" as GF
    participant "Infraestrutura Mapbox" as Map <<system>>

    
    API -> GF : Consultar Grafo (Interesses + Perfil)
    activate GF
    GF --> API : Lista de IDs de Atividades
    deactivate GF

    API -> Map : Consultar distância
    activate Map
    Map --> API : Retorna Distâncias
    deactivate Map


    API -> API : Organizar por relevância
    activate API

    API -> View : Apresentar Lista de Atividades
    deactivate API
    

    activate View
    deactivate View

    == Visualizar Detalhes (Extend) ==

    ' O usuário interage com a interface que foi gerada
    User -> View : Selecionar Atividade
    
    ' A Interface notifica o Controller (retorno tracejado da ação)
    View --> API : Retorna Seleção (ID da Atividade)
    deactivate View

    API -> GF : Buscar todos os detalhes da atividade
    activate GF
    GF --> API : Detalhes da Atividade + Link Externo
    deactivate GF
    
    ' Controller manda a interface apresentar os dados finais
    API -> View : Apresentar Página de Detalhes
    activate View
    deactivate API

@enduml