@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype ortho

package "Camada de Apresentação (Frontend)" as Presentation {
    [Interface Web] as UI
}

package "Camada de Aplicação (Backend Java)" as App {
    
        package "Services" as Domain_Logic {
        [SistemadeRecomendacao] <<service>>
        [IntegradorMapbox] <<service>>

    }
}

package "Camada de Dados" as DataLayer {
    [RepositoriodeAtividades] <<gateway>>
    
}

package "Serviços Externos" as External {
    [Mapbox API] <<system>>
}

' Fluxo lógico de dependência

Presentation ..> API : JSON/HTTP
API --> App
App --> DataLayer : Solicita dados
App ..> External : Consulta coordenadas

@enduml