@startuml


class Usuario {
}

class Instituicao {
   
}

class Categoria {
    Nome
}

class Atividade {
    
}

' Relacionamentos
Instituicao "1" -- "*" Atividade : Gerencia
Categoria "1..*" -- "1..*" Atividade : Contem
Categoria -[hidden]down- Atividade
Usuario "*" -- "*" Categoria : Se interessa/Busca
Usuario "*" -- "*" Atividade : Visualiza/Busca
Usuario "*" -- "*" Instituicao : Visualiza/Busca


@enduml